name: Build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - Dockerfile
jobs:
  image:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bndigital/github-actions-runner:latest
          build-args: |
            GITHUB_ORGANIZATION=bn-digital
            RUNNER_TOKEN=${{ secrets.RUNNER_TOKEN }}
